
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLE STOPstart : tabletable : BEGINTABLE skiptag handlerow handlerow handlerow handlerow handlerow  handlerow handlerow\n | skiptag :  CLOSEROW skiptag\n               | emptyhandlerow : OPENROW handleheader dataCell CLOSEROW handlerow           \n    | OPENROW handleheader CLOSEROW\n    | dataCell : OPENDATA content CLOSEDATA  dataCell \n    | OPENDATA content handlehref content CLOSEDATA dataCell\n    | OPENDATA handlehref content CLOSEDATA dataCell\n                | handlehref : OPENHREF content CLOSEHREF handlehref\n\t| handleheader : OPENHEADER CONTENT CLOSEHEADER handleheader\n                    | OPENHEADER CONTENT CONTENT CONTENT CLOSEHEADER handleheader\n                    | OPENHEADER content handlehref CLOSEHEADER handleheader\n                    | emptyempty :content : CONTENT content\n               | emptyContent : CONTENT Content\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([0,1,2,3,4,5,6,7,9,10,14,16,21,22,31,32,40,47,],[-3,0,-1,-19,-8,-19,-5,-8,-4,-8,-8,-7,-8,-8,-8,-6,-8,-2,]),'CLOSEROW':([3,5,8,11,13,15,28,33,38,39,41,43,45,46,48,49,51,52,],[5,5,-19,16,-18,22,-19,-12,-15,-19,-9,-12,-19,-17,-12,-11,-16,-10,]),'OPENROW':([3,4,5,6,7,9,10,14,16,21,22,31,32,40,],[-19,8,-19,-5,8,-4,8,8,-7,8,8,8,-6,8,]),'OPENHEADER':([8,28,39,45,],[12,12,12,12,]),'OPENDATA':([8,11,13,28,33,38,39,43,45,46,48,51,],[-19,17,-18,-19,17,-15,-19,17,-19,-17,17,-16,]),'CONTENT':([12,17,18,20,23,24,25,26,27,29,34,37,44,50,],[18,25,27,-21,-14,25,25,25,37,-20,25,25,-14,-13,]),'OPENHREF':([12,17,18,19,20,23,25,27,29,37,44,],[-19,26,-19,26,-21,26,-19,-19,-20,-19,26,]),'CLOSEHEADER':([12,18,19,20,25,27,29,30,37,44,50,],[-19,28,-14,-21,-19,-19,-20,39,45,-14,-13,]),'CLOSEDATA':([17,20,23,24,25,29,34,35,42,44,50,],[-14,-21,33,-19,-19,-20,-19,43,48,-14,-13,]),'CLOSEHREF':([20,25,26,29,36,],[-21,-19,-19,-20,44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,],[4,9,]),'empty':([3,5,8,12,17,18,24,25,26,27,28,34,37,39,45,],[6,6,13,20,20,20,20,20,20,20,13,20,20,13,13,]),'handlerow':([4,7,10,14,21,22,31,40,],[7,10,14,21,31,32,40,47,]),'handleheader':([8,28,39,45,],[11,38,46,51,]),'dataCell':([11,33,43,48,],[15,41,49,52,]),'content':([12,17,18,24,25,26,27,34,37,],[19,23,29,35,29,36,29,42,29,]),'handlehref':([17,19,23,44,],[24,30,34,50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','DOBandrole.py',87),
  ('table -> BEGINTABLE skiptag handlerow handlerow handlerow handlerow handlerow handlerow handlerow','table',9,'p_table','DOBandrole.py',91),
  ('table -> <empty>','table',0,'p_table','DOBandrole.py',92),
  ('skiptag -> CLOSEROW skiptag','skiptag',2,'p_skiptag','DOBandrole.py',95),
  ('skiptag -> empty','skiptag',1,'p_skiptag','DOBandrole.py',96),
  ('handlerow -> OPENROW handleheader dataCell CLOSEROW handlerow','handlerow',5,'p_handlerow','DOBandrole.py',99),
  ('handlerow -> OPENROW handleheader CLOSEROW','handlerow',3,'p_handlerow','DOBandrole.py',100),
  ('handlerow -> <empty>','handlerow',0,'p_handlerow','DOBandrole.py',101),
  ('dataCell -> OPENDATA content CLOSEDATA dataCell','dataCell',4,'p_dataCell','DOBandrole.py',113),
  ('dataCell -> OPENDATA content handlehref content CLOSEDATA dataCell','dataCell',6,'p_dataCell','DOBandrole.py',114),
  ('dataCell -> OPENDATA handlehref content CLOSEDATA dataCell','dataCell',5,'p_dataCell','DOBandrole.py',115),
  ('dataCell -> <empty>','dataCell',0,'p_dataCell','DOBandrole.py',116),
  ('handlehref -> OPENHREF content CLOSEHREF handlehref','handlehref',4,'p_handlehref','DOBandrole.py',127),
  ('handlehref -> <empty>','handlehref',0,'p_handlehref','DOBandrole.py',128),
  ('handleheader -> OPENHEADER CONTENT CLOSEHEADER handleheader','handleheader',4,'p_handleheader','DOBandrole.py',133),
  ('handleheader -> OPENHEADER CONTENT CONTENT CONTENT CLOSEHEADER handleheader','handleheader',6,'p_handleheader','DOBandrole.py',134),
  ('handleheader -> OPENHEADER content handlehref CLOSEHEADER handleheader','handleheader',5,'p_handleheader','DOBandrole.py',135),
  ('handleheader -> empty','handleheader',1,'p_handleheader','DOBandrole.py',136),
  ('empty -> <empty>','empty',0,'p_empty','DOBandrole.py',151),
  ('content -> CONTENT content','content',2,'p_content','DOBandrole.py',155),
  ('content -> empty','content',1,'p_content','DOBandrole.py',156),
  ('Content -> CONTENT Content','Content',2,'p_Content','DOBandrole.py',163),
  ('Content -> empty','Content',1,'p_Content','DOBandrole.py',164),
]
